@startwbs sitemap_student
* Classroom management
** List subscribed classes
*** View presences
@endwbs

@startwbs sitemap_teacher
* Classroom management
** List sessions
*** Edit presences
@endwbs

@startwbs sitemap
* Classroom management
** List subscribed classes
*** View presences
** List sessions
*** Edit session details
*** Edit presences
** List classes
*** Add class
*** View class details
*** Edit class details
*** Add session
*** Subscribe student to class
** List students
*** Add student
*** View student details
*** Edit student details
** List teachers
*** Add teacher
*** View teacher details
*** Edit teacher details
** Grant roles to people
** List courses
*** Add course
*** Edit course details
** List Sections
*** Add Section
** List academic year
*** Add academic year
@endwbs

@startuml conception_classes
left to right direction
skinparam nodesep 100
skinparam ranksep 120

class Section {
  name
}
class Person {
  firstName
  lastName
  emailAddress
  phoneNumber
}
class Course {
  name
}
class CourseClass {
  identifier
  capacity
}
class Session {
  day
  beginningTime
  endTime
}
class Presence {
  status
  periods
}
class AcademicYear {
  beginningYear
  endYear
}

class Role {
  name
}

Section "1..*" o-- "1..*" Course
Course "1" <- "0..*" CourseClass : instantiates <
AcademicYear "1" *-- "1..*" CourseClass
CourseClass "0..*" --> "teacher\n1..*" Person
CourseClass "0..*" --> "students\n0..*" Person
CourseClass "1" *- "0..*" Session
Role "0..*" <- "0..*" Person : is granted <
Person "1" <- "0..*" Presence : concerns <
Session "1" -- "0..*" Presence : concerns <
@enduml

@startuml inheritance_zoom_before
left to right direction
skinparam nodesep 100
skinparam ranksep 120

class Person {
  firstName
  lastName
  emailAddress
}
class Student {
  phoneNumber
}
class Teacher
class Class {
  identifier
  capacity
}

Person <|-- Teacher
Person <|-- Student
Teacher -- Class : teaches >
Student -- Class : is subscribed to >
@enduml

@startuml inheritance_zoom_after
left to right direction
skinparam nodesep 100
skinparam ranksep 120

class Person {
  firstName
  lastName
  emailAddress
  phoneNumber
}
class Class {
  identifier
  capacity
}
class Role {
  name
}

Person "teacher\n0..*" -- "0..*" Class
Person "students\n0..*" -- "0..*" Class
Person "1" - "0..*" Role : is granted >
@enduml

@startuml bidirectional_association
left to right direction
skinparam nodesep 100
skinparam ranksep 120

class Role {
  name
}

class Person {
  firstName
  lastName
  emailAddress
  phoneNumber
}

class Class {
  identifier
  capacity
}
class Session {
  day
  beginningTime
  endTime
}
class Presence {
  status
  periods
}

Class "0..*" -- "teacher\n1..*" Person
Class "0..*" -- "students\n0..*" Person
Class "1" *- "0..*" Session
Role "0..*" - "0..*" Person : is granted <
Person "1" - "0..*" Presence : concerns <
Session "1" -- "0..*" Presence : concerns <
@enduml

@startuml unidirectional_association
left to right direction
skinparam nodesep 100
skinparam ranksep 120

class Role {
  name
}

class Person {
  firstName
  lastName
  emailAddress
  phoneNumber
}

class Class {
  identifier
  capacity
}
class Session {
  day
  beginningTime
  endTime
}
class Presence {
  status
  periods
}

Class "0..*" --> "teacher\n1..*" Person
Class "0..*" --> "students\n0..*" Person
Class "1" *- "0..*" Session
Role "0..*" <- "0..*" Person : is granted <
Person "1" <- "0..*" Presence : concerns <
Session "1" -- "0..*" Presence : concerns <
@enduml

@startuml manytomany
left to right direction
skinparam nodesep 100
skinparam ranksep 120

class Person {
  firstName
  lastName
  emailAddress
  phoneNumber
}

class Session {
  day
  beginningTime
  endTime
}

class Presence {
  status
  periods
}

Person "0..*" -- "0..*" Session
(Person, Session) .. Presence
@enduml

@startuml onetomanytoone
left to right direction
skinparam nodesep 50
skinparam ranksep 80

class Person {
  firstName
  lastName
  emailAddress
  phoneNumber
}

class Session {
  day
  beginningTime
  endTime
}

class Presence {
  status
  periods
}

note bottom of Presence
Max one presence per person per session
end note

Person "1" -- "0..*" Presence
Presence "0..*" -- "1" Session

@enduml

@startuml inheritance_alternative_before
left to right direction
skinparam nodesep 60
skinparam ranksep 80

class Reservation
class Customer
class Passenger
class Person {
  firstName
  lastName
}
class Address {
  line1
  line2
  city
  zipCode
  country
}

Person <|-- Customer
Person <|-- Passenger
Customer "1" -- "1..*" Reservation
Passenger "1" -- "1..*" Reservation
Person "1" - "1..*" Address
@enduml

@startuml inheritance_alternative_after
left to right direction
skinparam nodesep 60
skinparam ranksep 80

class Reservation
class Customer
class Passenger
class ContactDetails {
  firstName
  lastName
}
class Address {
  line1
  line2
  city
  zipCode
  country
}
ContactDetails "1" -- "0..1" Customer
ContactDetails "1" -- "0..1" Passenger
Customer "1" -- "1..*" Reservation
Passenger "1" -- "1..*" Reservation
ContactDetails "1" - "1..*" Address
@enduml
