@startuml conception_classes
left to right direction
skinparam nodesep 100
skinparam ranksep 120

class Section {
  -name : String
}
class AcademicYear {
  -beginning : LocalDate
  -end : LocalDate
  +contains(date : LocalDate) : boolean
}
class Person {
  firstName
  lastName
  emailAddress
  phoneNumber
}
class Course {
  name
}
class CourseClass {
  identifier
  capacity
}
class Session {
  day
  beginningTime
  endTime
}
class Presence {
  status
  periods
}

class Role {
  name
}

Section "1..*" o--> "1..*" Course
Course "1" <- "0..*" CourseClass : instantiates <
AcademicYear "1" *-- "1..*" CourseClass
CourseClass "0..*" --> "teacher\n1..*" Person
CourseClass "0..*" --> "students\n0..*" Person
CourseClass "1" *- "0..*" Session
Role "0..*" <- "0..*" Person : is granted <
Person "1" <- "0..*" Presence : concerns <
Session "1" -- "0..*" Presence : concerns <
@enduml
