@baseurl = http://localhost:8080

GET {{baseurl}}/api/v1/sections
Accept: application/json
Origin: "http://localhost:3000/"

###

POST {{baseurl}}/api/v1/sections
Accept: application/json
Content-Type: application/json

{
  "name": "Informatique et systèmes"
}

###

POST {{baseurl}}/api/v1/sections
Accept: application/json
Content-Type: application/json

{
  "name": "Informatique de gestion"
}
