GET http://localhost:8080/api/v1/sections
Accept: application/json

###

POST http://localhost:8080/api/v1/sections
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InY1OG51c3JVbjBUbEYtZkFvVTJuTSJ9.eyJpc3MiOiJodHRwczovL2Rldi1wcm9qaW50LWExLTIxMjIuZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYyOTBkYjNlNmJkZDNkMDA2ZjE1YjY4MCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBpIiwiaHR0cHM6Ly9kZXYtcHJvamludC1hMS0yMTIyLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NTM2NjkzNzksImV4cCI6MTY1Mzc1NTc3OSwiYXpwIjoiUmdhSVZpYThkRHBoNVB6ck45OFdvczhyeEZVZ2VWdlMiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.lXuHoctSV6Uxsck-EVHHV5tohOGA6Ffo3q-az36v1QFvHxdWPEMYcuOj_lPuCMcUihkg6VtTASrANPJfZ1-OER2hWiYIRxwagZcsBj7y82O-h3O6wMozYpHY04RNw2IRBYpPv7P0YdpeVMSpJv6p9qCgB-pHrSiXge0zK0qqObVu4DWIztUnHStaqwbPLPQ8sXjbnciiyxEJbW64BisedaaSCRDVCjLtqDA1-jCjMg0CGBwOaqYJ-wndEM9CluykVYlwzazljyPOyHLi2o4WuW-N06gDyi84mWd23QY5qwKtW3rkwOnU4SMhKUv8l4ZWjyJWFH-wxXKcKJogZI-3IQ

{
  "name": "Informatique de gestion"
}

###

POST http://localhost:8080/api/v1/sections
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InY1OG51c3JVbjBUbEYtZkFvVTJuTSJ9.eyJpc3MiOiJodHRwczovL2Rldi1wcm9qaW50LWExLTIxMjIuZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYyOTBkYjNlNmJkZDNkMDA2ZjE1YjY4MCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBpIiwiaHR0cHM6Ly9kZXYtcHJvamludC1hMS0yMTIyLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NTM2NjkzNzksImV4cCI6MTY1Mzc1NTc3OSwiYXpwIjoiUmdhSVZpYThkRHBoNVB6ck45OFdvczhyeEZVZ2VWdlMiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.lXuHoctSV6Uxsck-EVHHV5tohOGA6Ffo3q-az36v1QFvHxdWPEMYcuOj_lPuCMcUihkg6VtTASrANPJfZ1-OER2hWiYIRxwagZcsBj7y82O-h3O6wMozYpHY04RNw2IRBYpPv7P0YdpeVMSpJv6p9qCgB-pHrSiXge0zK0qqObVu4DWIztUnHStaqwbPLPQ8sXjbnciiyxEJbW64BisedaaSCRDVCjLtqDA1-jCjMg0CGBwOaqYJ-wndEM9CluykVYlwzazljyPOyHLi2o4WuW-N06gDyi84mWd23QY5qwKtW3rkwOnU4SMhKUv8l4ZWjyJWFH-wxXKcKJogZI-3IQ

{
  "name": "Informatique et système"
}
