auth0:
  audience: http://localhost:8080/api/v1
spring:
  security:
    oauth2:
        resourceserver:
            jwt:
                issuer-uri: https://projint-froland-dev.eu.auth0.com/
  devtools:
    livereload:
      enabled: false
